name: PROOF Orchestrator CI/CD
on:
  push:
    branches:
      - test_ci
    tags:
      - 'v*'
env:
  GITHUB_TOKEN: ${{ secrets.PROOF_PACKAGE_CI_TOKEN }}

jobs:
  build:
    if: github.ref_type != 'tag' && !startsWith(github.event.head_commit.message, 'WIP')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Cache Maven packages
      #  uses: actions/cache@v4
      #  with:
      #    path: ~/.m2
      #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-m2-

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
          server-id: 'github-proof'
          server-password: GITHUB_TOKEN
      - run: mvn clean compile test

  deploy:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: 'github-proof'
          server-password: GITHUB_TOKEN

      - name: Checkout CI scripts
        uses: actions/checkout@v4
        with:
          repository: kit-iai-proof/proof-ci-scripts
          path: ci-scripts
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}


      #- name: Cache Maven packages
      #  uses: actions/cache@v4
      #  with:
      #    path: ~/.m2
      #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-m2-

      - name: Setup path for scripts
        run: echo "$GITHUB_WORKSPACE/ci-scripts" >> "$GITHUB_PATH"

      - name: Verify version
        run: ./ci-scripts/check-mvn-git-project-version-match

      - name: Login to GHCR
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      # Necessary because GitHub Actions does not allow to use uppercase letters in the image name, but the repository owner may contain uppercase letters.
      - name: Normalize image name
        run: |
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Maven clean
        run: mvn clean

      - name: Build and push image with Jib
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          
          mvn \
            install \
            com.google.cloud.tools:jib-maven-plugin:3.4.6:build \
            -Dimage=ghcr.io/${IMAGE_OWNER}/${{ github.event.repository.name }}:${VERSION}

      - name: Prepare post-deploy
        uses: actions/upload-artifact@v4
        with:
          name: generated
          path: generated/
          retention-days: 1

  post-deploy-maven:
    if: false #github.ref_type == 'tag'
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: generated
          path: generated/

      - name: Inspect files
        run: |
          pwd
          ls -R

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: 'github-proof'
          server-password: GITHUB_TOKEN

      - name: Run client deployment
        working-directory: generated/java
        run: mvn clean deploy -DaltDeploymentRepository=github-proof::https://maven.pkg.github.com/KIT-IAI-PROOF/proof-maven-packages -f pom.xml

  post-deploy-npm:
    if: github.ref_type == 'tag'
    needs: deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: generated
          path: generated

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'

      - name: List npm files
        working-directory: generated/typescript
        run: ls -la

      #- name: Debug npm environment
      #  working-directory: generated/typescript
      #  run: |
      #    node --version
      #    npm --version
      #    npm ls typescript || true
      #    npx tsc --version

      - name: Publish npm package
        working-directory: generated/typescript
        run: | 
          npm install --include=dev
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}